### zeros()

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 2次元以降はタプルで指定

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### ones()

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### full

In [9]:
np.full(3,7)

array([7, 7, 7])

In [10]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### empty

In [11]:
np.empty(5)

array([1., 1., 1., 1., 1.])

### zeros_like

In [12]:
a = np.full((2,3),5)

In [13]:
a

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
b = np.full((2,3,4),0)

In [16]:
b

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [17]:
np.zeros_like(b)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

### ones_like

In [18]:
np.ones_like(b)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### full_like

In [19]:
np.full_like(b, 2)

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

### empty_like

In [20]:
np.empty_like(b)

array([[[ 423390712,        512,         58,          0],
        [         0,          0,          0,          0],
        [         0,         50, 1852990827,  825125989]],

       [[ 892350520,  758736230, 1647916337, 1717908525],
        [ 892939569,  925721656,  828716594,  875902054],
        [ 774910049, 1667594341, 1600484469, 1970496882]]])