### rand()

In [1]:
import numpy as np

In [2]:
np.random.rand()

0.8094170509995853

In [3]:
np.random.rand(5)

array([0.29556639, 0.63605555, 0.72463903, 0.3237037 , 0.63290696])

In [4]:
np.random.rand(2,5)

array([[0.72952089, 0.28775941, 0.13988488, 0.45417939, 0.24040137],
       [0.04919874, 0.4798179 , 0.47672443, 0.03417115, 0.6086822 ]])

### random_sample()

In [5]:
np.random.random_sample()

0.4730639916938715

In [6]:
np.random.random_sample((2,5))

array([[0.05146195, 0.29095254, 0.46934032, 0.86952606, 0.1561996 ],
       [0.54585222, 0.03792347, 0.74181283, 0.33636513, 0.46772941]])

### randint()

In [7]:
np.random.randint(10)

0

In [8]:
np.random.randint(10, size=3)

array([1, 2, 3])

In [9]:
np.random.randint(10, size=(2, 3))

array([[9, 0, 5],
       [7, 1, 2]])

In [10]:
np.random.randint(10, size=(4, 3, 2))

array([[[3, 3],
        [5, 5],
        [6, 4]],

       [[7, 7],
        [3, 7],
        [0, 3]],

       [[0, 1],
        [6, 3],
        [2, 8]],

       [[9, 0],
        [8, 0],
        [0, 5]]])

### randn()

In [11]:
np.random.randn()

-1.690529924633985

In [12]:
np.random.randn(5)

array([-0.32130033, -2.04338567, -0.21861484,  0.47384298,  0.31455352])

In [13]:
np.random.randn(2, 3)

array([[-0.56254443,  1.08525695,  0.54513047],
       [-0.9931421 ,  0.9433992 ,  0.50526059]])