## 配列のスライス操作

In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[:3]

array([0, 1, 2])

In [5]:
a[7:]

array([7, 8, 9])

In [6]:
a[4:7]

array([4, 5, 6])

In [7]:
a[::2]

array([0, 2, 4, 6, 8])

In [8]:
a[1::2]

array([1, 3, 5, 7, 9])

In [9]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 多次元配列のスライス

In [10]:
a = np.array([[11,2,4,5],[7,8,9,0],[2,4,57,10]])

In [11]:
a

array([[11,  2,  4,  5],
       [ 7,  8,  9,  0],
       [ 2,  4, 57, 10]])

### 行

In [12]:
a[0,:]

array([11,  2,  4,  5])

In [13]:
a[2,:]

array([ 2,  4, 57, 10])

### 列

In [14]:
a[:,0]

array([11,  7,  2])

In [15]:
a[:,2]

array([ 4,  9, 57])

In [16]:
a

array([[11,  2,  4,  5],
       [ 7,  8,  9,  0],
       [ 2,  4, 57, 10]])

In [17]:
a[:2,:2]

array([[11,  2],
       [ 7,  8]])