## append（追加）

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
np.append(a,[6, 7])

array([1, 2, 3, 4, 5, 6, 7])

### 2次元配列へのappend

In [4]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.append(a, [[7,8,9]] , axis=0) #axis = 0 0次元

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.append(a, [[7], [8]] , axis=1) #axis = 1 1次元

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [8]:
np.append(a, [[7], [8]])

array([1, 2, 3, 4, 5, 6, 7, 8])

## insert(挿入)

In [9]:
a = np.array([1, 2, 3, 4, 5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [11]:
np.insert(a, 2, [6,7]) 

array([1, 2, 6, 7, 3, 4, 5])

### 2次元配列へのinsert

In [12]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [13]:
np.insert(a, 1, [[7,8,9]] , axis=0)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [14]:
np.insert(a, 2, [[7], [8]], axis=1)

array([[1, 2, 7, 8, 3],
       [4, 5, 7, 8, 6]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.insert(a, 1, [7, 8])

array([1, 7, 8, 2, 3, 4, 5, 6])

## delete（削除）

In [17]:
a = np.array([1, 2, 3, 4, 5])

In [18]:
np.delete(a,2)

array([1, 2, 4, 5])

### 二次元配列のdelete

In [19]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [20]:
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
np.delete(a,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
np.delete(a,1)

array([1, 3, 4, 5, 6, 7, 8, 9])