## Sort関数

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=10)

In [3]:
a

array([2, 7, 8, 5, 2, 2, 1, 4, 8, 8])

In [4]:
np.sort(a)

array([1, 2, 2, 2, 4, 5, 7, 8, 8, 8])

In [5]:
a= np.array([[7, 3, 9], [1, 8, 10], [9, 6, 2]])

## Sort関数は並び替えた結果を返す

In [6]:
a

array([[ 7,  3,  9],
       [ 1,  8, 10],
       [ 9,  6,  2]])

### 二次元配列のソート

In [7]:
a

array([[ 7,  3,  9],
       [ 1,  8, 10],
       [ 9,  6,  2]])

In [8]:
np.sort(a, axis=0)

array([[ 1,  3,  2],
       [ 7,  6,  9],
       [ 9,  8, 10]])

In [9]:
np.sort(a, axis=1)

array([[ 3,  7,  9],
       [ 1,  8, 10],
       [ 2,  6,  9]])

### Sortメソッド

In [10]:
a = np.random.randint(10, size=10)

In [11]:
a

array([9, 7, 8, 4, 8, 7, 9, 1, 0, 6])

In [12]:
a.sort()

## Sortメソッドは配列を並び替える

In [13]:
a

array([0, 1, 4, 6, 7, 7, 8, 8, 9, 9])

In [14]:
a= np.array([[7, 3, 9], [1, 8, 10], [9, 6, 2]])

In [15]:
a

array([[ 7,  3,  9],
       [ 1,  8, 10],
       [ 9,  6,  2]])

In [16]:
a.sort(axis=0)

In [17]:
a

array([[ 1,  3,  2],
       [ 7,  6,  9],
       [ 9,  8, 10]])

In [18]:
a= np.array([[7, 3, 9], [1, 8, 10], [9, 6, 2]])

In [19]:
a.sort(axis=1)

In [20]:
a

array([[ 3,  7,  9],
       [ 1,  8, 10],
       [ 2,  6,  9]])