In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(8, 3)

In [3]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### split関数

In [4]:
b = np.split(a, 2, axis=0) #縦に2つ

In [5]:
b

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])]

In [6]:
b[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
b = np.split(a, 4, axis=0) #縦に4つ

In [8]:
b

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]

In [9]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
b = np.split(a, [2,7], axis=0) # 分割位置をリストで指定できる

In [11]:
b

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]]),
 array([[21, 22, 23]])]

In [12]:
a = np.arange(24).reshape(3, 8)

In [13]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
b = np.split(a, 2, axis=1) #横に2つ

In [15]:
b

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

### vsplit関数（より簡単に使える）

In [16]:
a = np.arange(24).reshape(8, 3)

In [17]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [18]:
b = np.vsplit(a, 4)

In [20]:
b

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]

In [21]:
b[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b0, b1 = np.vsplit(a, 2)

In [23]:
b0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
b1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### hsplit関数

In [25]:
a = np.arange(24).reshape(3, 8)

In [26]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
b0,b1,b2 = np.hsplit(a,[2,5])

In [28]:
b0

array([[ 0,  1],
       [ 8,  9],
       [16, 17]])

In [29]:
b1

array([[ 2,  3,  4],
       [10, 11, 12],
       [18, 19, 20]])

In [31]:
b2

array([[ 5,  6,  7],
       [13, 14, 15],
       [21, 22, 23]])