In [1]:
import numpy as np

In [2]:
a = np.arange(36).reshape(3,4,3)

In [3]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

### flip関数（縦横反転）

In [4]:
np.flip(a)

array([[[35, 34, 33],
        [32, 31, 30],
        [29, 28, 27],
        [26, 25, 24]],

       [[23, 22, 21],
        [20, 19, 18],
        [17, 16, 15],
        [14, 13, 12]],

       [[11, 10,  9],
        [ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])

### flip関数（縦反転）

In [5]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [6]:
np.flip(a, axis=0) #最初の軸（0次元）が反転

array([[[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

### flip関数（横反転）

In [7]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [8]:
np.flip(a, axis=1) #2番目の軸（1次元）が反転

array([[[ 9, 10, 11],
        [ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[21, 22, 23],
        [18, 19, 20],
        [15, 16, 17],
        [12, 13, 14]],

       [[33, 34, 35],
        [30, 31, 32],
        [27, 28, 29],
        [24, 25, 26]]])

In [9]:
np.flip(a, axis=2) #3番目の軸が反転

array([[[ 2,  1,  0],
        [ 5,  4,  3],
        [ 8,  7,  6],
        [11, 10,  9]],

       [[14, 13, 12],
        [17, 16, 15],
        [20, 19, 18],
        [23, 22, 21]],

       [[26, 25, 24],
        [29, 28, 27],
        [32, 31, 30],
        [35, 34, 33]]])

### flipud関数（上下反転）

In [10]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [11]:
np.flipud(a) #最初の軸（0次元）が反転

array([[[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

### fliplr関数（左右反転）

In [12]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [13]:
np.fliplr(a) #2番目の軸（1次元）が反転

array([[[ 9, 10, 11],
        [ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[21, 22, 23],
        [18, 19, 20],
        [15, 16, 17],
        [12, 13, 14]],

       [[33, 34, 35],
        [30, 31, 32],
        [27, 28, 29],
        [24, 25, 26]]])