In [1]:
import numpy as np

### 乱数のシードを設定

In [2]:
np.random.seed(0)

### forループでべき乗の計算

In [5]:
def compute_squares(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] **2 
    return output

In [6]:
values = np.random.randint(1, 10, size = 5)
print(values)
compute_squares(values)

[4 6 3 5 8]


array([16., 36.,  9., 25., 64.])

### %timeitマジックコマンドで実行時間を計測

In [7]:
values = np.random.randint(1, 10, size = 1000000)
%timeit compute_squares(values) # %timeit Magicコマンド

605 ms ± 31.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 100万回の計算に1秒ほど掛かっているので、ベクトル演算にしてみる

In [8]:
values = np.random.randint(1, 10, size = 1000000)
%timeit values **2 # %timeit Magicコマンド

1.62 ms ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### ループ操作しないベクトル演算だと2.5ms 

In [9]:
a = np.arange(6).reshape(2, 3)

In [10]:
a

array([[0, 1, 2],
       [3, 4, 5]])

### ベクトル演算の練習

In [11]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a * 3

array([[ 0,  3,  6],
       [ 9, 12, 15]])