In [1]:
import numpy as np

## 単項ユニバーサル関数（ufunc）

In [2]:
a = np.arange(-10,10)

In [3]:
a

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

### abs関数:絶対値

In [4]:
np.abs(a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [5]:
a = np.arange(10)

### sqrt関数:平方根

In [6]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
a = np.arange(12).reshape(3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

### square():二乗

In [10]:
np.square(a)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

### exp():eを底としたべき乗

In [11]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [12]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### log():底eの自然対数

In [13]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

### log10():底が10

In [14]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

### sin()

In [15]:
a = np.arange(-10,10)

In [16]:
np.sin(a)

array([ 0.54402111, -0.41211849, -0.98935825, -0.6569866 ,  0.2794155 ,
        0.95892427,  0.7568025 , -0.14112001, -0.90929743, -0.84147098,
        0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### cos()

In [17]:
np.cos(a)

array([-0.83907153, -0.91113026, -0.14550003,  0.75390225,  0.96017029,
        0.28366219, -0.65364362, -0.9899925 , -0.41614684,  0.54030231,
        1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

### tan()

In [18]:
np.tan(a)

array([-0.64836083,  0.45231566,  6.79971146, -0.87144798,  0.29100619,
        3.38051501, -1.15782128,  0.14254654,  2.18503986, -1.55740772,
        0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])