In [1]:
import numpy as np

In [2]:
a = np.random.randn(3, 4)

In [3]:
a

array([[-0.21223807,  0.06369239, -0.32187158,  0.36301478],
       [ 1.76189748, -0.77776294,  0.11804204, -1.21407575],
       [ 0.59553604,  0.84442115, -0.71304521,  1.04000187]])

### sum関数

In [4]:
np.sum(a)

1.5476122016972784

In [5]:
sum(a) # 間違えてPythonのsum関数を実行すると

array([ 2.14519545,  0.1303506 , -0.91687474,  0.1889409 ])

### sumメソッド

In [6]:
a.sum()

1.5476122016972784

### prod関数:要素の積

In [7]:
np.prod(a)

-0.00011567685443454834

In [8]:
a.prod()

-0.00011567685443454834

### mean関数:平均値

In [9]:
a

array([[-0.21223807,  0.06369239, -0.32187158,  0.36301478],
       [ 1.76189748, -0.77776294,  0.11804204, -1.21407575],
       [ 0.59553604,  0.84442115, -0.71304521,  1.04000187]])

In [10]:
np.mean(a)

0.1289676834747732

### meanメソッド

In [11]:
a.mean()

0.1289676834747732

### max、min関数

In [12]:
np.max(a)

1.76189748285133

In [13]:
np.min(a)

-1.2140757516891314

### max、minメソッド

In [14]:
a.max()

1.76189748285133

In [15]:
a.min()

-1.2140757516891314

### std関数:標準偏差

In [16]:
a

array([[-0.21223807,  0.06369239, -0.32187158,  0.36301478],
       [ 1.76189748, -0.77776294,  0.11804204, -1.21407575],
       [ 0.59553604,  0.84442115, -0.71304521,  1.04000187]])

In [17]:
np.std(a)

0.8134161597412263

In [18]:
a.std()

0.8134161597412263

### var関数:分散値

In [19]:
np.var(a)

0.6616458489281641

In [20]:
a.var()

0.6616458489281641