In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[3]=1

In [5]:
a[9]=7

In [6]:
a

array([0, 1, 2, 1, 4, 5, 6, 7, 8, 7])

### 重複を取り除く

In [7]:
np.unique(a)

array([0, 1, 2, 4, 5, 6, 7, 8])

In [8]:
a = np.ones((4,5,6), dtype="float")

In [9]:
a

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [10]:
np.unique(a)

array([1.])

In [11]:
a = np.array([0, 1, 2, 1, 1, 6, 6, 7, 8, 7])

In [12]:
a

array([0, 1, 2, 1, 1, 6, 6, 7, 8, 7])

unique配列と抽出要素のインデックスを取得

In [13]:
np.unique(a, return_index=True)

(array([0, 1, 2, 6, 7, 8]), array([0, 1, 2, 5, 7, 8], dtype=int64))

unique配列と要素の個数

In [14]:
np.unique(a, return_counts=True)

(array([0, 1, 2, 6, 7, 8]), array([1, 3, 1, 2, 2, 1], dtype=int64))

### 別々に取り出す

In [15]:
x, y = np.unique(a, return_index=True)

In [16]:
x

array([0, 1, 2, 6, 7, 8])

In [17]:
y

array([0, 1, 2, 5, 7, 8], dtype=int64)

In [18]:
x, y = np.unique(a, return_counts=True)

In [19]:
x

array([0, 1, 2, 6, 7, 8])

In [20]:
y

array([1, 3, 1, 2, 2, 1], dtype=int64)