In [1]:
import numpy as np

In [2]:
x = np.loadtxt("m_data.txt",delimiter="\t", skiprows=1)

In [3]:
x

array([[ 1. , 19.2, 16.8, 17.7, 21. , 19.5],
       [ 2. , 12.4, 13.8, 14.5, 11.1, 15.6],
       [ 3. , 16.8, 17.2, 15.6, 17.8, 18.1],
       [ 4. , 19.4, 18.7, 18.5, 18.3, 18.9],
       [ 5. , 17.8, 17.4, 18.1, 17.8, 17.4]])

### スライス操作で最初の列以外

In [4]:
x1 = x[:,1:]

In [5]:
x1

array([[19.2, 16.8, 17.7, 21. , 19.5],
       [12.4, 13.8, 14.5, 11.1, 15.6],
       [16.8, 17.2, 15.6, 17.8, 18.1],
       [19.4, 18.7, 18.5, 18.3, 18.9],
       [17.8, 17.4, 18.1, 17.8, 17.4]])

### meanメソッド

In [6]:
x1.mean()

17.176

### スライス操作で1行目の1列以外

In [7]:
x1_1 = x[0,1:]

In [8]:
x1_1

array([19.2, 16.8, 17.7, 21. , 19.5])

In [9]:
x1_1.mean()

18.84

### そしてx1を保存

In [10]:
np.savetxt("m_data_save.csv", x1, delimiter=",")

### 小数点以下1桁までを指定

In [11]:
np.savetxt("m_data_save.csv", x1, delimiter=",", fmt="%.1f")