In [1]:
import numpy as np

In [2]:
data = np.loadtxt("m_data.csv",delimiter=",", skiprows=1)

In [3]:
data

array([[ 1. , 19.2, 16.8, 17.7, 21. , 19.5],
       [ 2. , 12.4, 13.8, 14.5, 11.1, 15.6],
       [ 3. , 16.8, 17.2, 15.6, 17.8, 18.1],
       [ 4. , 19.4, 18.7, 18.5, 18.3, 18.9],
       [ 5. , 17.8, 17.4, 18.1, 17.8, 17.4]])

### skiprows=1がskip_header=1に変わるだけで、同じように読み込める

In [4]:
data = np.genfromtxt("m_data.csv",delimiter=",",skip_header=1)

In [5]:
data

array([[ 1. , 19.2, 16.8, 17.7, 21. , 19.5],
       [ 2. , 12.4, 13.8, 14.5, 11.1, 15.6],
       [ 3. , 16.8, 17.2, 15.6, 17.8, 18.1],
       [ 4. , 19.4, 18.7, 18.5, 18.3, 18.9],
       [ 5. , 17.8, 17.4, 18.1, 17.8, 17.4]])

### 欠損値があると、どうだろうか

In [6]:
data = np.loadtxt("m_data2.csv",delimiter=",", skiprows=1)

ValueError: could not convert string '' to float64 at row 2, column 3.

In [7]:
data = np.genfromtxt("m_data2.csv",delimiter=",",skip_header=1)

In [8]:
data

array([[ 1. , 19.2, 16.8, 17.7, 21. , 19.5],
       [ 2. , 12.4, 13.8, 14.5, 11.1, 15.6],
       [ 3. , 16.8,  nan,  nan, 17.8, 18.1],
       [ 4. , 19.4, 18.7, 18.5, 18.3, 18.9],
       [ 5. , 17.8, 17.4, 18.1, 17.8, 17.4]])

### np.genfromtxt()を使うと欠損値がnp.nanとして読み込まれる

### 引数filling_valuesに欠損値を埋める値を指定できる

In [9]:
data = np.genfromtxt("m_data2.csv",delimiter=",",skip_header=1,filling_values=10)

In [10]:
data

array([[ 1. , 19.2, 16.8, 17.7, 21. , 19.5],
       [ 2. , 12.4, 13.8, 14.5, 11.1, 15.6],
       [ 3. , 16.8, 10. , 10. , 17.8, 18.1],
       [ 4. , 19.4, 18.7, 18.5, 18.3, 18.9],
       [ 5. , 17.8, 17.4, 18.1, 17.8, 17.4]])