# array関数による配列の作成

## リストやタプルから配列を作成する

In [1]:
import numpy as np
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.array((1,2,3,4,5,6,7,8,9,10))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## データ型を指定する

In [3]:
np.array([1,2,3,4,5] ,dtype="float64")

array([1., 2., 3., 4., 5.])

In [4]:
np.array([1.2,2,3.14,4,5] ,dtype="int32")

array([1, 2, 3, 4, 5])

### データ型の一覧 