## 二次元配列

In [20]:
import numpy as np
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [21]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### ndim属性で次元がわかる

In [22]:
a.ndim

2

### shape属性で形状がわかる

In [4]:
a.shape

(2, 5)

## リスト内包表記で2次元配列を作る

In [5]:
b = np.array([range(i, i + 5) for i in [1, 3, 5]])

In [6]:
b

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [7]:
b.shape

(3, 5)

In [8]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
c.ndim

3

In [11]:
c.shape

(2, 2, 2)

In [12]:
d = np.array([[[0 for k in range(3)] for j in range(5)] for i in range(4)])

In [17]:
d

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [13]:
d.shape

(4, 5, 3)

In [14]:
e = np.array([[[k * j * i for k in range(1,4)] for j in range(1,6)] for i in range(1,5)])

In [15]:
e

array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12],
        [ 5, 10, 15]],

       [[ 2,  4,  6],
        [ 4,  8, 12],
        [ 6, 12, 18],
        [ 8, 16, 24],
        [10, 20, 30]],

       [[ 3,  6,  9],
        [ 6, 12, 18],
        [ 9, 18, 27],
        [12, 24, 36],
        [15, 30, 45]],

       [[ 4,  8, 12],
        [ 8, 16, 24],
        [12, 24, 36],
        [16, 32, 48],
        [20, 40, 60]]])

In [16]:
e.shape

(4, 5, 3)