In [6]:
import numpy as np
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])

### dtype

In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.array([1.01,2.22,3.89,4.,5.11])

In [9]:
b.dtype

dtype('float64')

In [10]:
c = np.array([[[k * j * i for k in range(1,4)] for j in range(1,6)] for i in range(1,5)], dtype='int16' )

In [11]:
c.dtype

dtype('int16')

### shape

In [12]:
a.shape

(2, 5)

In [13]:
b.shape

(5,)

In [3]:
c.shape

(4, 5, 3)

### ndim


In [14]:
a.ndim

2

In [15]:
b.ndim

1

In [16]:
c.ndim

3

### size

In [17]:
a.size

10

In [18]:
b.size

5

In [19]:
c.size

60

### T

In [20]:
a.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [21]:
c.T

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16],
        [ 5, 10, 15, 20]],

       [[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32],
        [10, 20, 30, 40]],

       [[ 3,  6,  9, 12],
        [ 6, 12, 18, 24],
        [ 9, 18, 27, 36],
        [12, 24, 36, 48],
        [15, 30, 45, 60]]], dtype=int16)

In [22]:
c

array([[[ 1,  2,  3],
        [ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12],
        [ 5, 10, 15]],

       [[ 2,  4,  6],
        [ 4,  8, 12],
        [ 6, 12, 18],
        [ 8, 16, 24],
        [10, 20, 30]],

       [[ 3,  6,  9],
        [ 6, 12, 18],
        [ 9, 18, 27],
        [12, 24, 36],
        [15, 30, 45]],

       [[ 4,  8, 12],
        [ 8, 16, 24],
        [12, 24, 36],
        [16, 32, 48],
        [20, 40, 60]]], dtype=int16)

In [23]:
d = c.T

In [7]:
d

array([[[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16],
        [ 5, 10, 15, 20]],

       [[ 2,  4,  6,  8],
        [ 4,  8, 12, 16],
        [ 6, 12, 18, 24],
        [ 8, 16, 24, 32],
        [10, 20, 30, 40]],

       [[ 3,  6,  9, 12],
        [ 6, 12, 18, 24],
        [ 9, 18, 27, 36],
        [12, 24, 36, 48],
        [15, 30, 45, 60]]], dtype=int16)

In [8]:
d.shape

(3, 5, 4)