## 配列のインデックス操作

In [1]:
import numpy as np

In [2]:
a = np.arange(1,6)

In [3]:
a

array([1, 2, 3, 4, 5])

### 参照

In [4]:
a[3]

4

### 代入

In [5]:
a[0] = 0

In [6]:
a

array([0, 2, 3, 4, 5])

### 2次元配列

In [7]:
b = np.random.randint(10, size=(3, 5))

In [8]:
b

array([[5, 9, 1, 4, 9],
       [8, 0, 7, 5, 8],
       [9, 9, 8, 2, 4]])

In [9]:
b[0][3]

4

In [10]:
b[1][2]= 3

In [11]:
b[1]

array([8, 0, 3, 5, 8])

In [12]:
b[2][3] = 4

In [13]:
b

array([[5, 9, 1, 4, 9],
       [8, 0, 3, 5, 8],
       [9, 9, 8, 4, 4]])