## view()

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size=(3,3,3 ))

In [3]:
a

array([[[8, 6, 2],
        [2, 4, 1],
        [0, 8, 6]],

       [[7, 4, 9],
        [8, 2, 7],
        [5, 6, 2]],

       [[3, 2, 9],
        [7, 1, 8],
        [1, 1, 5]]])

In [4]:
b = a.view()

In [7]:
b[1][1][1] = 15

In [5]:
b

array([[[8, 6, 2],
        [2, 4, 1],
        [0, 8, 6]],

       [[7, 4, 9],
        [8, 2, 7],
        [5, 6, 2]],

       [[3, 2, 9],
        [7, 1, 8],
        [1, 1, 5]]])

In [6]:
a

array([[[8, 6, 2],
        [2, 4, 1],
        [0, 8, 6]],

       [[7, 4, 9],
        [8, 2, 7],
        [5, 6, 2]],

       [[3, 2, 9],
        [7, 1, 8],
        [1, 1, 5]]])

### copy()

In [7]:
a = np.random.randint(10, size=(3,3,3 ))

In [8]:
a

array([[[8, 4, 8],
        [5, 3, 5],
        [1, 2, 8]],

       [[7, 9, 8],
        [6, 4, 6],
        [9, 5, 7]],

       [[0, 1, 4],
        [3, 5, 6],
        [5, 7, 8]]])

In [9]:
c = a.copy()

In [10]:
c[1][1][1]=100

In [12]:
c

array([[[  8,   4,   8],
        [  5,   3,   5],
        [  1,   2,   8]],

       [[  7,   9,   8],
        [  6, 100,   6],
        [  9,   5,   7]],

       [[  0,   1,   4],
        [  3,   5,   6],
        [  5,   7,   8]]])

In [13]:
a

array([[[8, 4, 8],
        [5, 3, 5],
        [1, 2, 8]],

       [[7, 9, 8],
        [6, 4, 6],
        [9, 5, 7]],

       [[0, 1, 4],
        [3, 5, 6],
        [5, 7, 8]]])