In [1]:
import numpy as np

In [2]:
a = np.arange(3)

In [3]:
a

array([0, 1, 2])

In [4]:
b = np.arange(3,6)

In [5]:
b

array([3, 4, 5])

### concatenate関数

In [6]:
np.concatenate([a,b]) #リストで指定

array([0, 1, 2, 3, 4, 5])

### 2次元の場合

In [7]:
a = np.arange(16)

In [8]:
a1 = a.reshape([4, 4])

In [9]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
b = np.arange(16,20)

In [11]:
b1 = b.reshape([1, 4]) #二次元配列同士に

In [12]:
np.concatenate([a1, b1], 0) # axis = 0 0次元

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
b1

array([[16, 17, 18, 19]])

In [15]:
b

array([16, 17, 18, 19])

In [16]:
b2 = b.reshape([4, 1]) 

In [17]:
b2

array([[16],
       [17],
       [18],
       [19]])

In [18]:
np.concatenate([a1, b2], 1) # axis = 1　1次元

array([[ 0,  1,  2,  3, 16],
       [ 4,  5,  6,  7, 17],
       [ 8,  9, 10, 11, 18],
       [12, 13, 14, 15, 19]])

### stack関数

In [19]:
a = np.array([1,2,3,4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
b = np.array([5,6])

In [22]:
b

array([5, 6])

In [23]:
np.stack([a, b]) # ValueError: all input arrays must have the same shape

ValueError: all input arrays must have the same shape

In [25]:
b = np.array([5,6,7,8])

In [26]:
np.stack([a, b]) # 二次元配列になる

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
np.stack([a, b],1) # axis = 1を指定

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 二次元配列では

In [28]:
c = np.stack([a, b],1)

In [29]:
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
c.shape

(4, 2)

In [31]:
d = np.array([[5,9],[6,10],[7,11],[8,12]])

In [32]:
d.shape

(4, 2)

In [33]:
e = np.stack([c,d]) # 3次元になる

In [34]:
e

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 5,  9],
        [ 6, 10],
        [ 7, 11],
        [ 8, 12]]])

In [35]:
e.shape

(2, 4, 2)

In [36]:
e.ndim

3

In [37]:
e = np.stack([c,d],1) # axis = 1を指定

In [38]:
e

array([[[ 1,  5],
        [ 5,  9]],

       [[ 2,  6],
        [ 6, 10]],

       [[ 3,  7],
        [ 7, 11]],

       [[ 4,  8],
        [ 8, 12]]])

In [39]:
e.shape

(4, 2, 2)

In [40]:
e.ndim

3

### vstack（縦方向に繋げる）

In [41]:
a = np.arange(12).reshape(2, 3, 2)

In [42]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [43]:
a.ndim

3

In [44]:
b = np.arange(6).reshape(1, 3, 2)

In [45]:
b

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [46]:
c = np.vstack([a,b])

In [47]:
c.shape

(3, 3, 2)

### hstack（横方向に繋げる）

In [48]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [49]:
a.shape

(2, 3, 2)

In [50]:
d = np.arange(4).reshape(2, 1, 2)

In [51]:
d

array([[[0, 1]],

       [[2, 3]]])

In [52]:
e = np.hstack([a,d])

In [53]:
e.shape

(2, 4, 2)

In [54]:
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 0,  1]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [ 2,  3]]])

### block関数（引数のリストで配列の配置を指定できる）

In [55]:
a = np.arange(12).reshape(3, 4)

In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b = np.arange(8).reshape(2, 4)

In [58]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [59]:
c = np.block([[a],[b]])

In [60]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [61]:
c.ndim

2

In [62]:
d = np.block([[[a]],[[a]]])

In [63]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [64]:
d.ndim

3

In [65]:
d.shape

(2, 3, 4)