In [1]:
import numpy as np

### roll関数（シフト）

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.roll(a,3)

array([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

### マイナスを指定すると

In [5]:
np.roll(a,-3)

array([3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

### 二次元だと

In [6]:
a = np.arange(36).reshape(3,12)

In [7]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [8]:
np.roll(a,6)

array([[30, 31, 32, 33, 34, 35,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### 軸を指定すると

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [10]:
np.roll(a,2,axis=0)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [11]:
np.roll(a,6,axis=1)

array([[ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23, 12, 13, 14, 15, 16, 17],
       [30, 31, 32, 33, 34, 35, 24, 25, 26, 27, 28, 29]])

### 3次元

In [12]:
a = np.arange(36).reshape(3,4,3)

In [13]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [14]:
np.roll(a,2,axis=0) #0次元

array([[[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [15]:
np.roll(a,2,axis=1) #1次元

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  1,  2],
        [ 3,  4,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [12, 13, 14],
        [15, 16, 17]],

       [[30, 31, 32],
        [33, 34, 35],
        [24, 25, 26],
        [27, 28, 29]]])

In [16]:
np.roll(a,2,axis=2) #2次元

array([[[ 1,  2,  0],
        [ 4,  5,  3],
        [ 7,  8,  6],
        [10, 11,  9]],

       [[13, 14, 12],
        [16, 17, 15],
        [19, 20, 18],
        [22, 23, 21]],

       [[25, 26, 24],
        [28, 29, 27],
        [31, 32, 30],
        [34, 35, 33]]])

In [17]:
np.roll(a,1,axis=2) #2次元

array([[[ 2,  0,  1],
        [ 5,  3,  4],
        [ 8,  6,  7],
        [11,  9, 10]],

       [[14, 12, 13],
        [17, 15, 16],
        [20, 18, 19],
        [23, 21, 22]],

       [[26, 24, 25],
        [29, 27, 28],
        [32, 30, 31],
        [35, 33, 34]]])