## 二項ユニバーサル関数

In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
b = np.array([[ 1,  3,  2,  3],
       [ 4,  5,  7,  9],
       [ 5,  9, 1, 11],
       [5, 13, 7, 15]])

In [5]:
b

array([[ 1,  3,  2,  3],
       [ 4,  5,  7,  9],
       [ 5,  9,  1, 11],
       [ 5, 13,  7, 15]])

### add関数

In [6]:
np.add(a,b)

array([[ 1,  4,  4,  6],
       [ 8, 10, 13, 16],
       [13, 18, 11, 22],
       [17, 26, 21, 30]])

### subtract関数

In [7]:
np.subtract(a,b)

array([[-1, -2,  0,  0],
       [ 0,  0, -1, -2],
       [ 3,  0,  9,  0],
       [ 7,  0,  7,  0]])

### multiply関数

In [8]:
np.multiply(a,b)

array([[  0,   3,   4,   9],
       [ 16,  25,  42,  63],
       [ 40,  81,  10, 121],
       [ 60, 169,  98, 225]])

### divide関数

In [9]:
np.divide(a,b)

array([[ 0.        ,  0.33333333,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  0.85714286,  0.77777778],
       [ 1.6       ,  1.        , 10.        ,  1.        ],
       [ 2.4       ,  1.        ,  2.        ,  1.        ]])

### mod関数:剰余

In [10]:
np.mod(a,b)

array([[0, 1, 0, 0],
       [0, 0, 6, 7],
       [3, 0, 0, 0],
       [2, 0, 0, 0]])

### power関数:べき乗

In [11]:
np.power(a,b)

array([[          0,           1,           4,          27],
       [        256,        3125,      279936,    40353607],
       [      32768,   387420489,          10,  1843829075],
       [     248832, -1692154371,   105413504,  1500973039]])