In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.arange(100,110)

In [5]:
b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [6]:
a + b

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

### ブロードキャスト

In [7]:
a + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
c = np.arange(5)

In [9]:
c

array([0, 1, 2, 3, 4])

### Error

In [10]:
c + b

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

### ブロードキャスト可能な例

In [11]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a * 2 #単一の値

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

(n, m) 対 (n, 1)

In [13]:
a = np.arange(6).reshape(3,2)

In [14]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
b = np.arange(3).reshape(3,1)

In [16]:
b

array([[0],
       [1],
       [2]])

In [17]:
a + b

array([[0, 1],
       [3, 4],
       [6, 7]])

(n, m) 対 (1, m)

In [18]:
a = np.arange(6).reshape(2,3)

In [19]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b = np.arange(3).reshape(1,3)

In [21]:
b

array([[0, 1, 2]])

In [22]:
a - b

array([[0, 0, 0],
       [3, 3, 3]])

### 3次元配列

In [23]:
a = np.arange(12).reshape(2,3,2)

In [24]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [25]:
b = np.array([2,2])

In [26]:
b

array([2, 2])

In [27]:
a * b

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])